apiVersion: apps/v1
kind: Deployment
metadata:
  name: drplan-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: DrPlan
  template:
    metadata:
      labels:
        app: DrPlan
    spec:
      containers:
        - name: web
          image: 253490772403.dkr.ecr.ap-northeast-2.amazonaws.com/drplan
          imagePullPolicy: Always
          ports:
            - containerPort: 8080


