apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- DrPlan-deployment.yaml
- DrPlan-service.yaml
- DrPlan-ingress.yaml
- fluentbit-configmap.yaml
- fluentbit-serviceaccount.yaml
- fluentbit-daemonset.yaml
images:
- name: 253490772403.dkr.ecr.ap-northeast-2.amazonaws.com/drplan
  newName: 253490772403.dkr.ecr.ap-northeast-2.amazonaws.com/drplan
  newTag: 9bfa5a49
